### ISSUE TITLE
[Message] Another Markdown scheme

### ISSUE THREAD

**Issue by boolbag** [marek-stoj/EditPad-Pro-Markdown#2]
Howdy Marek,

Hope this finds you well.

After using your Markdown scheme every once in a while for some time now, thought I'd reach out as your idea inspired me to make a new `md` scheme from scratch to go with [MishMash, a new EPP color palette](https://github.com/boolbag/EditPad-Goodies/tree/master/Making%20Text%20Pretty%20-%20Syntax%20Coloring%20and%20Color%20Palettes/Color%20Palettes) I had made. 

Of course you are mentioned on the that [MarkDown page](https://github.com/boolbag/Autohotkey-Goodies/tree/master/Syntax%20Coloring%20Scheme%20for%20EditPad%20Pro), in fact  this lives on a repo called [EditPad Goodies](https://github.com/boolbag/EditPad-Goodies), the intention being to share EPP tools with anyone who'd like to collaborate (you are warmly invited). 

This is not meant to be an open issue, please close, I just thought my message had a better chance of reaching you this way than via email.

Wishing you a beautiful week

Rex

![demo](https://user-images.githubusercontent.com/7551671/57985796-a9c82180-7a6d-11e9-8f88-f19a0c34c9f3.jpg)

**Comment by marek-stoj** [comment]
Hi!

That's cool. I really like the palette. However, I've switched almost exclusively to OS X and Atom/VS Code a while ago. But to be honest, I really miss EditPad - its ability to handle very large files and the way search/replace using regular expressions is implemented - I couldn't find anything better to this day :)

Kind Regards,
Marek

**Comment by boolbag** [comment]
Ditto, for regex JG Soft has one of the best engines, which is one of the things that puts EPP on top for me.
And large files… Recently I tried a different editor that kept messing with my code. EPP is not beautiful but I love that it is industrial-strength.

Hope you enjoy your new set-up anyway! 
All the best.
